### ISSUE TITLE
Go dependencies can conflict with workspace's Go deps

### ISSUE THREAD

**Issue by pswaminathan** [cgrindel/swift_bazel#154]
Had a situation in implementation where I had to remove a bunch of dependencies that were common to my project and `swift_bazel`, but for which `swift_bazel` had an older (and incompatible) version of a prometheus library. I was getting this error:

```
ERROR: /private/var/tmp/_bazel_p/5462d161dadab65df3f9fb5a8ecf08b9/external/com_github_prometheus_common/expfmt/BUILD.bazel:3:11: GoCompilePkg external/com_github_prometheus_common/expfmt/expfmt.a failed: (Exit 1): builder failed: error executing command (from target @com_github_prometheus_common//expfmt:expfmt) bazel-out/darwin_arm64-opt-exec-2B5CBBC6/bin/external/go_sdk/builder compilepkg -sdk external/go_sdk -installsuffix darwin_arm64 -src external/com_github_prometheus_common/expfmt/decode.go -src ... (remaining 41 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
external/com_github_prometheus_common/expfmt/openmetrics_create.go:171:20: metric.Counter.Exemplar undefined (type *io_prometheus_client.Counter has no field or method Exemplar)
external/com_github_prometheus_common/expfmt/openmetrics_create.go:239:8: b.Exemplar undefined (type *io_prometheus_client.Bucket has no field or method Exemplar)
external/com_github_prometheus_common/expfmt/openmetrics_create.go:305:16: undefined: io_prometheus_client.Exemplar
external/com_github_prometheus_common/expfmt/openmetrics_create.go:448:45: undefined: io_prometheus_client.Exemplar
compilepkg: error running subcommand external/go_sdk/pkg/tool/darwin_arm64/compile: exit status 2
INFO: Elapsed time: 2.695s, Critical Path: 0.28s
INFO: 10 processes: 4 internal, 6 darwin-sandbox.
FAILED: Build did NOT complete successfully
```

Commenting out the `swift_bazel_go_dependencies` call would make my project succeed, but then would cause the gazelle targets to fail. I ended up manually copying over the go_deps file and removing all the duplicates.

**Comment by cgrindel** [comment]
The best idea that I have is to wrap the `go_repository` calls in `maybe`. As long as you declare your deps before calling `swift_bazel_go_dependencies`, yours should win. I will put up PR that adds the `maybe` wrappers. Let me know if you have a better idea.

**Comment by pswaminathan** [comment]
`maybe` is a good idea. It's like how most other repository rules work. The other option I can think of would be to make a new repository naming scheme for these. As in,

```
    go_repository(
        name = "swift_bazel_co_honnef_go_tools",
        build_external = "external",
        importpath = "honnef.co/go/tools",
        sum = "h1:/hemPrYIhOhy8zYrNj+069zDB68us2sMGsfkFJO0iZs=",
        version = "v0.0.0-20190523083050-ea95bdfd59fc",
    )
```

This would be similar to how e.g. [this project](https://github.com/grab/grab-bazel-common/blob/master/android/initialize.bzl#L35-L39) installs Maven dependencies in another repository namespace to avoid conflicts with the typical `maven` name. It's a little less ergonomic given Gazelle using a separate repository for each go dependency, but it would work. I don't know that I have a real opinion on which choice would be better here.
