### ISSUE TITLE
Xcode archive fails while stripping libSources_CCryptoBoringSSL.a

### ISSUE THREAD

**Issue by AttilaTheFun** [cgrindel/swift_bazel#182]
I managed to get one of my apps building on device with Bazel using rules_apple. build_bazel_rules_swift, rules_xcodeproj and this repository. Now I'm trying to distribute this app through TestFlight and creating an archive is failing with this error:

```
Strip /Users/logan/Library/Developer/Xcode/DerivedData/Stetho-hahzqdoycvgkdmbwoincidajiakj/Build/Intermediates.noindex/ArchiveIntermediates/Stetho/InstallationBuildProductsLocation/bazel-out/ios-arm64-min15.0-applebin_ios-ios_arm64-dbg-ST-68c5d89a16c6/bin/external/swiftpkg_swift_crypto/Sources_CCryptoBoringSSL/bin/libSources_CCryptoBoringSSL.a (in target 'Sources_CCryptoBoringSSL' from project 'Stetho')
    cd /Users/logan/Developer/Swift/Apps/Stetho
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/strip -S /Users/logan/Library/Developer/Xcode/DerivedData/Stetho-hahzqdoycvgkdmbwoincidajiakj/Build/Intermediates.noindex/ArchiveIntermediates/Stetho/InstallationBuildProductsLocation/bazel-out/ios-arm64-min15.0-applebin_ios-ios_arm64-dbg-ST-68c5d89a16c6/bin/external/swiftpkg_swift_crypto/Sources_CCryptoBoringSSL/bin/libSources_CCryptoBoringSSL.a

error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/strip: can't open file: /Users/logan/Library/Developer/Xcode/DerivedData/Stetho-hahzqdoycvgkdmbwoincidajiakj/Build/Intermediates.noindex/ArchiveIntermediates/Stetho/InstallationBuildProductsLocation/bazel-out/ios-arm64-min15.0-applebin_ios-ios_arm64-dbg-ST-68c5d89a16c6/bin/external/swiftpkg_swift_crypto/Sources_CCryptoBoringSSL/bin/libSources_CCryptoBoringSSL.a (No such file or directory)
```

**Comment by cgrindel** [comment]
I manually just built the `xcmetrics` example in the `swift_bazel` repo. It uses `swift-crypto`, as well. I do see libSources_CCryptoBoringSSL.a` being built. However, the path that I see is pretty different from the one that you are seeing.

```
bin/external/swiftpkg_swift_crypto/Sources_CCryptoBoringSSL/bin/libSources_CCryptoBoringSSL.a
```
versus
```
bin/external/swiftpkg_swift_crypto/libSources_CCryptoBoringSSL.a
```

I see that @brentleyjones [commented](https://github.com/bazelbuild/rules_apple/issues/1814#issuecomment-1405934309) about not using the Xcode archiving. Let us know if his suggestion works for you.

**Comment by AttilaTheFun** [comment]
Hi @cgrindel! I got further with a bazel-built IPA per Brentley's suggestion, using xcrun atool from Keith's gist:
https://github.com/bazelbuild/rules_apple/issues/1814#issuecomment-1406895462
But now it's failing validation because of the get-task-allow key which I guess rules_apple is adding automatically to the plist? Have you seen that issue before?

**Comment by cgrindel** [comment]
Unfortunately, no. I am not familiar with that issue.

**Comment by AttilaTheFun** [comment]
Ah he replied! I needed to build with `--compilation_mode=opt` to get a release build. Thanks!
