### ISSUE TITLE
README / release notes missing bazel_skylib_gazelle_plugin WORKSPACE dependency

### ISSUE THREAD

**Issue by AttilaTheFun** [cgrindel/swift_bazel#247]
Hi Chuck! I'm testing out the new release today and after copying the new WORKSPACE snippets I started getting the error:
```
no such package '@bazel_skylib_gazelle_plugin//bzl': The repository '@bazel_skylib_gazelle_plugin' could not be resolved: Repository '@bazel_skylib_gazelle_plugin' is not defined and referenced by '//:GazelleBinary'
```

I looked at your updated Firebase example and saw you're pulling this plugin in the example's WORKSPACE but not in the README or the release notes snippet.
https://github.com/cgrindel/swift_bazel/blob/main/examples/firebase_example/WORKSPACE#L23

Is this always required? If so it should probably be added to the documentation in both places.
If not, maybe add a comment saying when it's necessary? Thanks!

**Comment by cgrindel** [comment]
@AttilaTheFun Thanks for reporting this issue. 

The Skylib Gazelle plugin is not necessary for the `swift_bazel` plugin. I have been including the Skylib Gazelle plugin in the examples to help keep things tidy. I am inclined to remove the mention of the Skylib Gazelle plugin from the release snippets and the main README.md. However, I will leave the Skylib Gazelle plugin in the examples. Does that sound reasonable to you?

**Comment by AttilaTheFun** [comment]
Oh, is Gazelle not necessary at all to use the swift_bazel to generate Bazel targets from the Package.swift file? In general I think fewer dependencies is better. 

If that's the case I would remove Gazelle from the README and release snippets. Maybe add a separate folder with Gazelle examples + a separate README which you could link to as an optional addition.

**Comment by cgrindel** [comment]
We need Gazelle. We do not need the Skylib Gazelle plugin. #253 removes the reference to the Skylib Gazelle in the README.md. That should allow someone to copy the code from the README and get started using `swift_bazel`. Does that seem about right to you?

**Comment by AttilaTheFun** [comment]
Yeah that makes sense, thanks!
