### ISSUE TITLE
How to specify resource folder?

### ISSUE THREAD

**Issue by denis15yo** [cgrindel/swift_bazel#308]
Is there any way to specify the resources folder? I have the following in the Package.swift file
`resources: [.process("Resources")]`
This works in SPM but does not work in bazel

**Comment by denis15yo** [comment]
In my `Package.swift` I have an external dependency, one of whose targets contains resources specified as `resources: [.process("Resources")]`. The `swift_bazel` generates the following for it
```
apple_resource_bundle(
    name = "Sources_CoreUI_resource_bundle",
    bundle_name = "Sources_CoreUI_resource_bundle",
    infoplists = [":Sources_CoreUI_resource_bundle_infoplist"],
    resources = ["Sources/CoreUI/Resources"],
)
```
Since `Resources` is a folder, it would be great to see something like this
```
apple_resource_bundle(
    name = "Sources_CoreUI_resource_bundle",
    bundle_name = "Sources_CoreUI_resource_bundle",
    infoplists = [":Sources_CoreUI_resource_bundle_infoplist"],
    resources = glob(["Sources/CoreUI/Resources/**"]),
)
```

**Comment by cgrindel** [comment]
Can you send me the URL to the external Swift package so that I can debug this?

**Comment by denis15yo** [comment]
This is my private package, but I made a similar example https://github.com/denis15yo/res-example

**Comment by tingyao-ui** [comment]
I think I run into the same issue here.
I've used my own `Info.plist` as a template, reference from `Info-template.plist` of `rules_apple` example.
copy `Info-template.plist` into your project from https://github.com/bazelbuild/rules_apple/blob/master/test/testdata/resources/Info-template.plist

so the BUILD.bazel file will be like

```
apple_resource_bundle(
    name = "Sources_CoreUI_resource_bundle",
    bundle_name = "Sources_CoreUI_resource_bundle",
    infoplists = ["Info-template.plist"],
    resources = glob(["Sources/CoreUI/Resources/**"]),
)
```

or you may try the fix from my forked `swift_bazel` to see if it works.

[tingyao-ui/fix/eric-resource-bundle-plist-issue](https://github.com/tingyao-ui/swift_bazel/tree/fix/eric-resource-bundle-plist-issue)

**Comment by denis15yo** [comment]
Nothing seems to have changed when using the fork(

**Comment by cgrindel** [comment]
I am wrapping up some work adding bzlmod support. I should be able to take a look at this by early next week.

**Comment by cgrindel** [comment]
@denis15yo When you used the @tingyao-ui fork, did you keep the `glob()`?

@tingyao-ui It looks like [this](https://github.com/cgrindel/swift_bazel/compare/main...tingyao-ui:swift_bazel:fix/eric-resource-bundle-plist-issue) is the only change in your fork. Is that correct? If so, is there any reason I should not merge that change into `swift_bazel`?

**Comment by denis15yo** [comment]
@cgrindel Yes, I used the fork and then modified the generated BUILD file (added `glob()`). Just using the fork wasn't enough

**Comment by tingyao-ui** [comment]
I was going to create an issue and PR for this. It's a coincidence that I saw this issue with an example.
There is only one change on file `swiftpkg/internal/resource_bundle_info.plist.tmpl`, so yes, if it looks good to you please merge it. 🙂

**Comment by cgrindel** [comment]
@tingyao-ui I am working on a PR that will include your template change and @denis15yo `glob` change. I will ask you both to review it when it is ready.
