### ISSUE TITLE
Support target type `plugin` (module_type is `PluginTarget`)

### ISSUE THREAD

**Issue by cgrindel** [cgrindel/swift_bazel#46]
Currently, just treating it as a library.

**Comment by cgrindel** [comment]
Until we have a use-case for using plugins in Bazel, I am going to close this issue.

**Comment by GevaZeichner** [comment]
Another use case: https://github.com/securevale/swift-confidential

**Comment by cgrindel** [comment]
Revisiting — still relevant, still not implemented. Capturing the state for anyone picking this up:

**Current behavior:** SPM `PluginTarget` targets are treated as libraries. No PR has touched this since the issue was filed.

**Cited use cases:**

- [`grpc-swift` / `protoc-gen-grpc-swift`](https://github.com/grpc/grpc-swift/blob/main/Sources/protoc-gen-grpc-swift/Docs.docc/spm-plugin.md) — BuildPlugin that generates Swift code from `.proto` files (per @cgrindel's 2023-01-24 comment above).
- [`securevale/swift-confidential`](https://github.com/securevale/swift-confidential) — BuildPlugin that generates Swift files containing encrypted secrets (per @GevaZeichner's 2024-04-03 comment).

**Important distinction:** SPM `PluginTarget` is **not** the same as `swift_compiler_plugin` in `rules_swift`.

- SPM `PluginTarget` = BuildPlugin / CommandPlugin (SwiftPM invokes a Swift-built tool to generate code or run a task).
- `swift_compiler_plugin` = Swift compiler plugins = **Swift macros** (compile-time). That's tracked separately in `swift_gazelle_plugin#354`.

A fix for one does not cover the other.

**Rough fix shape:**

1. Detect `PluginTarget` in the SPM JSON dump (Go parser side — `tools/swift_deps_index/` area).
2. For **BuildPlugin**: translate to a `genrule` (or a small custom rule) that invokes the plugin binary with SwiftPM-shaped inputs/outputs.
3. For **CommandPlugin**: a `sh_binary`-style wrapper runnable via `bazel run` is probably enough.
4. Add an example in `examples/` exercising at least one case (grpc-swift is a good candidate since it's already widely known).
